version: '2.2'
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/nuc/appdata/nginx/data:/data
      - /home/nuc/appdata/nginx/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000
    ports:
      - 8081:80
    volumes:
      - /home/nuc:/srv
      - /home/nuc/appdata/filebrowser/filebrowser.db:/database.db #make sure filebrowser.db is created first
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale
    container_name: tailscaled
    volumes:
       - /var/lib:/var/lib
       - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
       - NET_ADMIN
       - NET_RAW
    environment:
      - TS_AUTHKEY=tskey-auth-<your unique auth key>
      - TS_STATE_DIR=/var/lib/tailscale
      #- TS_EXTRA_ARGS=--advertise-exit-node #uncomment if needed for this device
      #- TS_ROUTES=192.168.1.0/24 #uncomment if needed for this device
    restart: unless_stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - JELLYFIN_PublishedServerUrl=192.168.1.217
    volumes:
      - /home/nuc/appdata/jellyfin:/config
      - /home/nuc/media/tv:/data/tvshows
      - /home/nuc/media/movies:/data/movies
    ports:
      - '8096:8096'
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/nuc/appdata/sabnzbd:/config
      - /home/nuc/downloads/complete:/downloads
      - /home/nuc/downloads/incomplete:/incomplete-downloads
    ports:
      - '8080:8080'
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/nuc/appdata/sonarr:/config
      - /home/nuc/media/tv:/tv
      - /home/nuc/downloads/complete:/downloads
    ports:
      - '8989:8989'
    restart: unless-stopped
